const express = require('express')
const router = express.Router()
const authorController = require('../controllers/authorController')
const booksController = require('../controllers/booksController')
const pagesController = require('../controllers/pagesController')

router.get('/', authorController.home)
router.get('/author', authorController.index)
router.get('/author/new', authorController.new)
router.get('/author/:authorId', authorController.show)
router.get('/edit/author/:authorId', authorController.update)
router.post('/edit/author/:authorId', authorController.edit)
router.post('/author/create', authorController.create)
router.get('/author/delete/:authorId', authorController.delete)

router.get('/books', booksController.index)
router.get('/books/new', booksController.new)
router.get('/books/:booksId', booksController.show)
router.get('/edit/books/:booksId', booksController.update)
router.post('/edit/books/:booksId', booksController.edit)
router.post('/books/create', booksController.create)
router.get('/books/delete/:booksId', booksController.delete)

router.get('/pages', pagesController.index)
router.get('/pages/new', pagesController.new)
router.get('/pages/:pagesId', pagesController.show)
router.get('/edit/:pagesId', pagesController.update)
router.post('/edit/:pagesId', pagesController.edit)
router.post('/pages/create', pagesController.create)
router.get('/pages/delete/:pagesId', pagesController.delete)

module.exports = router